name: Notebook Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  execution:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    name: Execution
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: false
          environment-name: temp
          channels: defaults,conda-forge
          channel-priority: flexible
          extra-specs: |
            python=3.11
      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install notebook
      - name: Execute
        run: |
          jupyter nbconvert --to script split_comparisons.ipynb
          ipython split_comparisons.py
  compilation:
    needs: execution
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    name: Compilation
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Compile
        run: |
          quarto render split_comparisons.ipynb --to html
      - name: Push Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add split_comparisons.html split_comparisons_files/*
          git commit -m "Automated Quarto document update" -a || true
          git push
